name: Custom Windows VNC

on: 
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Getting Updates and Installing Tailscale, Git.
        run: |
          sudo apt update -y
          sudo apt install git wget tigervnc-standalone-server websockify novnc -y
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc
          sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null \
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main"
          sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update -y
          sudo apt install ngrok -y
          ngrok config add-authtoken 2bFmLPy2Pnmq673Nt2fidCw70ux_pk8P2PCkNUXbHiFyNn1x
          nohup ngrok http http://localhost:8006 &>/dev/null &
      - name: Copying Docker Container Files and Setting Everything Up.
        run: |
          git clone https://github.com/dockur/windows.git .
          rm Dockerfile
          wget -O loop.sh https://github.com/Efebey2903/GH-Ubuntu-Desktop/raw/main/loop.sh
          wget https://github.com/Efebey2903/Docker-VNC/raw/main/Dockerfile
          docker build -t dockerd .
          nohup docker run -i --name windows -p 8006:8006 --device=/dev/kvm -v  /mnt:/storage --cap-add NET_ADMIN --stop-timeout 99999990 dockerd &> /dev/null &
          sh loop.sh
